---
title: 'Extract Top Reddit Posts of #rstats in 3 lines of R Code '
author: AbdulMajedRaja RS
date: '2019-08-07 8:11:10'
slug: extract-top-reddit-posts-of-rstats-in-3-lines-of-r-code
categories:
  - Data Analysis
  - How-To
tags:
  - web scraping
  - hacks
  - tips and tricks
  - r-bloggers
description: 'using jsonlite'
topics: []
---

This post is kept (literally) minimal to demonstrate how simple is this hack using R (of course could be simple in other languages too). This is also to establish a point that R has got use-cases beyond statistics and data-mining. 

### Objective

`rstats` subreddit is one of the popular sources of R-related information / discussion on the internet. We're trying to extract the top posts of `rstats` subreddit. 

### Data Format

Lucky for us, Reddit offers a json file for every subreddit (also post) and we'll use that here.

``` html
subreddit url: "https://www.reddit.com/r/rstats/"
subreddit json: "https://www.reddit.com/r/rstats/.json"
```

### jsonlite @ Action 

The package that will help us in this endeavor is `jsonlite` (by **Jeroen Ooms** and Team) for parsing `json` files and feeds. It's got a sweet function that `fromJSON()` that parses a json file and stores the result in a `list` object. Ultimately, we can find the required information - `title`, `url` of the subreddit in there.

```{r}
library(jsonlite)

reddit <- fromJSON("https://www.reddit.com/r/rstats/.json")

(top10 <- reddit$data$children$data[1:10,c("title","url")])

```

### 3-lines

+ Load the library
+ Retrieve and Parse the json file
+ Extract the relevant information for the list object


### Summary

This post while is primarily intended to demonstrate the simplicity of R and `jsonlite` for json parsing, it can also be used to automate such a script to email or send notification about top 10 rstats subreddit post at a scheduled interval. 

### References

+ [rstats reddit](https://www.reddit.com/r/rstats/)
+ [jsonline - Github](https://github.com/jeroen/jsonlite)

### Read more

[Beginners Cookbook for Interactive Visualization in R with highcharter](https://www.programmingwithr.com/beginners-cookbook-for-interactive-visualization-in-r-with-highcharter/)


*If you like [our posts](https://www.programmingwithr.com/), Please share it with your Friends and Network. Use [our RSS Feed](https://www.programmingwithr.com/index.xml), to subscribe for latest update from [programmingwithr.com](https://www.programmingwithr.com/)*





